# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: decrementer.proto for package 'goaway'

require 'grpc'
require 'decrementer_pb'

module Goaway
  module Decrementer
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'goaway.Decrementer'

      rpc :Decrement, DecrementRequest, DecrementReply
    end

    Stub = Service.rpc_stub_class
  end
end
