# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: incrementer.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "goaway.IncrementRequest" do
  end
  add_message "goaway.IncrementReply" do
    optional :count, :int64, 1
  end
end

module Goaway
  IncrementRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("goaway.IncrementRequest").msgclass
  IncrementReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("goaway.IncrementReply").msgclass
end
