# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: incrementer.proto for package 'goaway'

require 'grpc'
require 'incrementer_pb'

module Goaway
  module Incrementer
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'goaway.Incrementer'

      rpc :Increment, IncrementRequest, IncrementReply
    end

    Stub = Service.rpc_stub_class
  end
end
